//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.19.0
//     from Assets/FishingActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/FishingActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @FishingActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @FishingActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""FishingActions"",
    ""maps"": [
        {
            ""name"": ""Player Inputs"",
            ""id"": ""bec96889-4afe-4c06-82ee-a02fe07d0361"",
            ""actions"": [
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""086783c0-bab2-480e-a551-5dcb5a9880ef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchBait"",
                    ""type"": ""Button"",
                    ""id"": ""9fcaab43-a32b-427c-91e9-07dd7db8f902"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel"",
                    ""type"": ""Button"",
                    ""id"": ""dc965847-f0ae-4a62-8203-76fe19190da1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 1"",
                    ""type"": ""Button"",
                    ""id"": ""75a22e15-86ff-4465-bddc-54c88304a15a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 2"",
                    ""type"": ""Button"",
                    ""id"": ""787521fc-336e-4a09-8d73-e83938f0e5d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 3"",
                    ""type"": ""Button"",
                    ""id"": ""4ab041fb-dd3a-4b93-9b2c-a85c97145189"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 4"",
                    ""type"": ""Button"",
                    ""id"": ""4c6c4df8-0f35-478e-9ed9-6c93e1789c60"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 5"",
                    ""type"": ""Button"",
                    ""id"": ""7e97596d-906d-486c-a758-9201c40aefa7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 6"",
                    ""type"": ""Button"",
                    ""id"": ""c13420d3-c3f7-4adf-966e-e236d38c7cae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 7"",
                    ""type"": ""Button"",
                    ""id"": ""c3e4d5fa-f025-465d-bf21-2e1e6df95687"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reel Button 8"",
                    ""type"": ""Button"",
                    ""id"": ""9a556849-4931-4617-8c1d-1141a2d0f446"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open/Close Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""39897f50-bd81-4829-a464-6fd27b98a48d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open/Close Map"",
                    ""type"": ""Button"",
                    ""id"": ""eb57815f-918d-4ed2-af55-df030b20d424"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MapPoint"",
                    ""type"": ""Value"",
                    ""id"": ""6e830de2-523c-4318-910e-0009f995b38b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MapDrag"",
                    ""type"": ""Button"",
                    ""id"": ""838816aa-656e-432c-9b3b-33a7a186b961"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MapZoom"",
                    ""type"": ""Value"",
                    ""id"": ""106b9874-a946-420f-9183-b8209fce521c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""117c9bdb-1c6b-46fc-8b88-dbf77938c575"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c2ffec4-59a8-452a-89ac-f85f75a8b2e5"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchBait"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a86fc833-ef43-4fb4-8c00-c8a686d13789"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4688f7c-284b-44b2-814d-9b4fa92c6fbd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0be9a743-a2af-47c9-873a-4105e6a65e51"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d5339ec-ec5f-45b3-a74c-493950a3ebb3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5acb29f-5163-41fe-971a-abfd537bb9d4"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55727ae1-8e29-4707-b520-c987e3064cc6"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""030003a6-3866-49ff-8260-b93c5ae66c86"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e07ce00-ea35-44dd-aeb7-6c6ffc88adab"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d551dee9-3559-49a4-a8c3-885c6e4af9ba"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reel Button 8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c87b111d-b31f-4169-bd0a-1643aa498847"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open/Close Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05afc1bd-36f9-448b-b742-1b958461bb46"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open/Close Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77afe94c-85be-41a3-bb27-6e4083d7ef70"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapPoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f5cb2bb2-81f4-4db8-834c-a1a31ebf764c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapDrag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d8f35f1-29ff-44cf-badb-fe2c64c94510"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MapZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player Inputs
        m_PlayerInputs = asset.FindActionMap("Player Inputs", throwIfNotFound: true);
        m_PlayerInputs_Throw = m_PlayerInputs.FindAction("Throw", throwIfNotFound: true);
        m_PlayerInputs_SwitchBait = m_PlayerInputs.FindAction("SwitchBait", throwIfNotFound: true);
        m_PlayerInputs_Reel = m_PlayerInputs.FindAction("Reel", throwIfNotFound: true);
        m_PlayerInputs_ReelButton1 = m_PlayerInputs.FindAction("Reel Button 1", throwIfNotFound: true);
        m_PlayerInputs_ReelButton2 = m_PlayerInputs.FindAction("Reel Button 2", throwIfNotFound: true);
        m_PlayerInputs_ReelButton3 = m_PlayerInputs.FindAction("Reel Button 3", throwIfNotFound: true);
        m_PlayerInputs_ReelButton4 = m_PlayerInputs.FindAction("Reel Button 4", throwIfNotFound: true);
        m_PlayerInputs_ReelButton5 = m_PlayerInputs.FindAction("Reel Button 5", throwIfNotFound: true);
        m_PlayerInputs_ReelButton6 = m_PlayerInputs.FindAction("Reel Button 6", throwIfNotFound: true);
        m_PlayerInputs_ReelButton7 = m_PlayerInputs.FindAction("Reel Button 7", throwIfNotFound: true);
        m_PlayerInputs_ReelButton8 = m_PlayerInputs.FindAction("Reel Button 8", throwIfNotFound: true);
        m_PlayerInputs_OpenCloseInventory = m_PlayerInputs.FindAction("Open/Close Inventory", throwIfNotFound: true);
        m_PlayerInputs_OpenCloseMap = m_PlayerInputs.FindAction("Open/Close Map", throwIfNotFound: true);
        m_PlayerInputs_MapPoint = m_PlayerInputs.FindAction("MapPoint", throwIfNotFound: true);
        m_PlayerInputs_MapDrag = m_PlayerInputs.FindAction("MapDrag", throwIfNotFound: true);
        m_PlayerInputs_MapZoom = m_PlayerInputs.FindAction("MapZoom", throwIfNotFound: true);
    }

    ~@FishingActions()
    {
        UnityEngine.Debug.Assert(!m_PlayerInputs.enabled, "This will cause a leak and performance issues, FishingActions.PlayerInputs.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player Inputs
    private readonly InputActionMap m_PlayerInputs;
    private List<IPlayerInputsActions> m_PlayerInputsActionsCallbackInterfaces = new List<IPlayerInputsActions>();
    private readonly InputAction m_PlayerInputs_Throw;
    private readonly InputAction m_PlayerInputs_SwitchBait;
    private readonly InputAction m_PlayerInputs_Reel;
    private readonly InputAction m_PlayerInputs_ReelButton1;
    private readonly InputAction m_PlayerInputs_ReelButton2;
    private readonly InputAction m_PlayerInputs_ReelButton3;
    private readonly InputAction m_PlayerInputs_ReelButton4;
    private readonly InputAction m_PlayerInputs_ReelButton5;
    private readonly InputAction m_PlayerInputs_ReelButton6;
    private readonly InputAction m_PlayerInputs_ReelButton7;
    private readonly InputAction m_PlayerInputs_ReelButton8;
    private readonly InputAction m_PlayerInputs_OpenCloseInventory;
    private readonly InputAction m_PlayerInputs_OpenCloseMap;
    private readonly InputAction m_PlayerInputs_MapPoint;
    private readonly InputAction m_PlayerInputs_MapDrag;
    private readonly InputAction m_PlayerInputs_MapZoom;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player Inputs".
    /// </summary>
    public struct PlayerInputsActions
    {
        private @FishingActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerInputsActions(@FishingActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/Throw".
        /// </summary>
        public InputAction @Throw => m_Wrapper.m_PlayerInputs_Throw;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/SwitchBait".
        /// </summary>
        public InputAction @SwitchBait => m_Wrapper.m_PlayerInputs_SwitchBait;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/Reel".
        /// </summary>
        public InputAction @Reel => m_Wrapper.m_PlayerInputs_Reel;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton1".
        /// </summary>
        public InputAction @ReelButton1 => m_Wrapper.m_PlayerInputs_ReelButton1;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton2".
        /// </summary>
        public InputAction @ReelButton2 => m_Wrapper.m_PlayerInputs_ReelButton2;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton3".
        /// </summary>
        public InputAction @ReelButton3 => m_Wrapper.m_PlayerInputs_ReelButton3;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton4".
        /// </summary>
        public InputAction @ReelButton4 => m_Wrapper.m_PlayerInputs_ReelButton4;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton5".
        /// </summary>
        public InputAction @ReelButton5 => m_Wrapper.m_PlayerInputs_ReelButton5;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton6".
        /// </summary>
        public InputAction @ReelButton6 => m_Wrapper.m_PlayerInputs_ReelButton6;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton7".
        /// </summary>
        public InputAction @ReelButton7 => m_Wrapper.m_PlayerInputs_ReelButton7;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/ReelButton8".
        /// </summary>
        public InputAction @ReelButton8 => m_Wrapper.m_PlayerInputs_ReelButton8;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/OpenCloseInventory".
        /// </summary>
        public InputAction @OpenCloseInventory => m_Wrapper.m_PlayerInputs_OpenCloseInventory;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/OpenCloseMap".
        /// </summary>
        public InputAction @OpenCloseMap => m_Wrapper.m_PlayerInputs_OpenCloseMap;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/MapPoint".
        /// </summary>
        public InputAction @MapPoint => m_Wrapper.m_PlayerInputs_MapPoint;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/MapDrag".
        /// </summary>
        public InputAction @MapDrag => m_Wrapper.m_PlayerInputs_MapDrag;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputs/MapZoom".
        /// </summary>
        public InputAction @MapZoom => m_Wrapper.m_PlayerInputs_MapZoom;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputs; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerInputsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerInputsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerInputsActions" />
        public void AddCallbacks(IPlayerInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputsActionsCallbackInterfaces.Add(instance);
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @SwitchBait.started += instance.OnSwitchBait;
            @SwitchBait.performed += instance.OnSwitchBait;
            @SwitchBait.canceled += instance.OnSwitchBait;
            @Reel.started += instance.OnReel;
            @Reel.performed += instance.OnReel;
            @Reel.canceled += instance.OnReel;
            @ReelButton1.started += instance.OnReelButton1;
            @ReelButton1.performed += instance.OnReelButton1;
            @ReelButton1.canceled += instance.OnReelButton1;
            @ReelButton2.started += instance.OnReelButton2;
            @ReelButton2.performed += instance.OnReelButton2;
            @ReelButton2.canceled += instance.OnReelButton2;
            @ReelButton3.started += instance.OnReelButton3;
            @ReelButton3.performed += instance.OnReelButton3;
            @ReelButton3.canceled += instance.OnReelButton3;
            @ReelButton4.started += instance.OnReelButton4;
            @ReelButton4.performed += instance.OnReelButton4;
            @ReelButton4.canceled += instance.OnReelButton4;
            @ReelButton5.started += instance.OnReelButton5;
            @ReelButton5.performed += instance.OnReelButton5;
            @ReelButton5.canceled += instance.OnReelButton5;
            @ReelButton6.started += instance.OnReelButton6;
            @ReelButton6.performed += instance.OnReelButton6;
            @ReelButton6.canceled += instance.OnReelButton6;
            @ReelButton7.started += instance.OnReelButton7;
            @ReelButton7.performed += instance.OnReelButton7;
            @ReelButton7.canceled += instance.OnReelButton7;
            @ReelButton8.started += instance.OnReelButton8;
            @ReelButton8.performed += instance.OnReelButton8;
            @ReelButton8.canceled += instance.OnReelButton8;
            @OpenCloseInventory.started += instance.OnOpenCloseInventory;
            @OpenCloseInventory.performed += instance.OnOpenCloseInventory;
            @OpenCloseInventory.canceled += instance.OnOpenCloseInventory;
            @OpenCloseMap.started += instance.OnOpenCloseMap;
            @OpenCloseMap.performed += instance.OnOpenCloseMap;
            @OpenCloseMap.canceled += instance.OnOpenCloseMap;
            @MapPoint.started += instance.OnMapPoint;
            @MapPoint.performed += instance.OnMapPoint;
            @MapPoint.canceled += instance.OnMapPoint;
            @MapDrag.started += instance.OnMapDrag;
            @MapDrag.performed += instance.OnMapDrag;
            @MapDrag.canceled += instance.OnMapDrag;
            @MapZoom.started += instance.OnMapZoom;
            @MapZoom.performed += instance.OnMapZoom;
            @MapZoom.canceled += instance.OnMapZoom;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerInputsActions" />
        private void UnregisterCallbacks(IPlayerInputsActions instance)
        {
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @SwitchBait.started -= instance.OnSwitchBait;
            @SwitchBait.performed -= instance.OnSwitchBait;
            @SwitchBait.canceled -= instance.OnSwitchBait;
            @Reel.started -= instance.OnReel;
            @Reel.performed -= instance.OnReel;
            @Reel.canceled -= instance.OnReel;
            @ReelButton1.started -= instance.OnReelButton1;
            @ReelButton1.performed -= instance.OnReelButton1;
            @ReelButton1.canceled -= instance.OnReelButton1;
            @ReelButton2.started -= instance.OnReelButton2;
            @ReelButton2.performed -= instance.OnReelButton2;
            @ReelButton2.canceled -= instance.OnReelButton2;
            @ReelButton3.started -= instance.OnReelButton3;
            @ReelButton3.performed -= instance.OnReelButton3;
            @ReelButton3.canceled -= instance.OnReelButton3;
            @ReelButton4.started -= instance.OnReelButton4;
            @ReelButton4.performed -= instance.OnReelButton4;
            @ReelButton4.canceled -= instance.OnReelButton4;
            @ReelButton5.started -= instance.OnReelButton5;
            @ReelButton5.performed -= instance.OnReelButton5;
            @ReelButton5.canceled -= instance.OnReelButton5;
            @ReelButton6.started -= instance.OnReelButton6;
            @ReelButton6.performed -= instance.OnReelButton6;
            @ReelButton6.canceled -= instance.OnReelButton6;
            @ReelButton7.started -= instance.OnReelButton7;
            @ReelButton7.performed -= instance.OnReelButton7;
            @ReelButton7.canceled -= instance.OnReelButton7;
            @ReelButton8.started -= instance.OnReelButton8;
            @ReelButton8.performed -= instance.OnReelButton8;
            @ReelButton8.canceled -= instance.OnReelButton8;
            @OpenCloseInventory.started -= instance.OnOpenCloseInventory;
            @OpenCloseInventory.performed -= instance.OnOpenCloseInventory;
            @OpenCloseInventory.canceled -= instance.OnOpenCloseInventory;
            @OpenCloseMap.started -= instance.OnOpenCloseMap;
            @OpenCloseMap.performed -= instance.OnOpenCloseMap;
            @OpenCloseMap.canceled -= instance.OnOpenCloseMap;
            @MapPoint.started -= instance.OnMapPoint;
            @MapPoint.performed -= instance.OnMapPoint;
            @MapPoint.canceled -= instance.OnMapPoint;
            @MapDrag.started -= instance.OnMapDrag;
            @MapDrag.performed -= instance.OnMapDrag;
            @MapDrag.canceled -= instance.OnMapDrag;
            @MapZoom.started -= instance.OnMapZoom;
            @MapZoom.performed -= instance.OnMapZoom;
            @MapZoom.canceled -= instance.OnMapZoom;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerInputsActions.UnregisterCallbacks(IPlayerInputsActions)" />.
        /// </summary>
        /// <seealso cref="PlayerInputsActions.UnregisterCallbacks(IPlayerInputsActions)" />
        public void RemoveCallbacks(IPlayerInputsActions instance)
        {
            if (m_Wrapper.m_PlayerInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerInputsActions.AddCallbacks(IPlayerInputsActions)" />
        /// <seealso cref="PlayerInputsActions.RemoveCallbacks(IPlayerInputsActions)" />
        /// <seealso cref="PlayerInputsActions.UnregisterCallbacks(IPlayerInputsActions)" />
        public void SetCallbacks(IPlayerInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerInputsActions" /> instance referencing this action map.
    /// </summary>
    public PlayerInputsActions @PlayerInputs => new PlayerInputsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player Inputs" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerInputsActions.AddCallbacks(IPlayerInputsActions)" />
    /// <seealso cref="PlayerInputsActions.RemoveCallbacks(IPlayerInputsActions)" />
    public interface IPlayerInputsActions
    {
        /// <summary>
        /// Method invoked when associated input action "Throw" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnThrow(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchBait" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchBait(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReel(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton4(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 5" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton5(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 6" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton6(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 7" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton7(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Reel Button 8" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnReelButton8(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Open/Close Inventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenCloseInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Open/Close Map" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenCloseMap(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MapPoint" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMapPoint(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MapDrag" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMapDrag(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MapZoom" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMapZoom(InputAction.CallbackContext context);
    }
}
